name: posnext_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  blue_thermal_printer: ^1.2.3

  # Add the intl package here
  intl: ^0.18.0  # (or use the latest version available on pub.dev)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  simple_barcode_scanner: ^0.0.8

flutter:
  uses-material-design: true